# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bde8a91d9f45ad2768d793469c8e7c59b9ff6a88078aafea7a759a80bf3482d61df394326b9742af9acc68fab3e38fc6f6d7baf01d9e2c77457110f83d11dd26

test:
  secret_key_base: 027486e73a5048d9cb872a6a9b4a3384d62fc56aa87d1e20cec6d9daf80b5159aa40db5ea173998d889106ef35d6677cfd4af5ee315d20e34ea4fe8473fda18b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
